[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
[functions] 
    node_bundler = "esbuild"
[dev]
    framework = "create-react-app"
    functionsPort = 3001
[[redirects]]
    from = "/*"
    to = "/"
    status = 200